# Generated by Django 2.0.3 on 2018-03-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProposedLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_user', models.CharField(max_length=200)),
                ('synset1id', models.IntegerField()),
                ('synset2id', models.IntegerField()),
            ],
        ),
    ]
