# Generated by Django 2.0.3 on 2018-03-23 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0002_auto_20180309_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposedlink',
            name='synset1def',
            field=models.TextField(default='no definition'),
        ),
        migrations.AlterField(
            model_name='proposedlink',
            name='synset2def',
            field=models.TextField(default='no definition'),
        ),
    ]
